//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public int EmpleadosID { get; set; }
        public string Nombre_Del_Empleado { get; set; }
        public string Apellido_Del_Empleado { get; set; }
        public System.DateTime FecNac { get; set; }
        public Nullable<int> Edad { get; set; }
        public decimal Numero_Telefonico { get; set; }
        public int CargoID { get; set; }
    
        public virtual Info_Cargo Info_Cargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
